name: ASP.NET API

on:
  push:
    branches: [ master ]
    paths:
      - 'GitHubActionsSample.Api/**'
      - 'GitHubActionsSample.Api.Tests/**'
      - '.github/workflows/api.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'GitHubActionsSample.Api/**'
      - 'GitHubActionsSample.Api.Tests/**'
      - '.github/workflows/api.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache@v3.0.8
        with:
          path: GitHubActionsSample.Api
          key: api-binaries
      - uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - run: dotnet build --configuration Release GitHubActionsSample.Api/GitHubActionsSample.Api.csproj
      - name: Test
        run: dotnet test GitHubActionsSample.Api.Tests/GitHubActionsSample.Api.Tests.csproj --verbosity normal
  publish:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Cache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache@v3.0.8
        with:
          path: GitHubActionsSample.Api
          key: api-binaries
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
