name: .NET Package

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'packages/GitHubActionsSample.Package/**'
      - 'tests/GitHubActionsSample.Package.Tests/**'
      - '.github/workflows/package.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'packages/GitHubActionsSample.Package/**'
      - 'tests/GitHubActionsSample.Package.Tests/**'
      - '.github/workflows/package.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache@v3.0.8
        with:
          path: packages/GitHubActionsSample.Package
          key: packages-binaries
      - uses: actions/setup-dotnet@v2.1.1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build --configuration Release packages/GitHubActionsSample.Package/GitHubActionsSample.Package.csproj
      - name: Test
        run: dotnet test tests/GitHubActionsSample.Package.Tests/GitHubActionsSample.Package.Tests.csproj --verbosity normal
  publish:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: packages/GitHubActionsSample.Package
          key: packages-binaries
      - name: Create the package
        run: dotnet pack --configuration Release packages/GitHubActionsSample.Package/GitHubActionsSample.Package.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push packages/GitHubActionsSample.Package/bin/Release/GitHubActionsSample.Package.*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/blaze6950/index.json
